### PR TITLE
Model validation

### LINKED ISSUE #42: Model Validation
Add checks to ensure the model is valid during boot and after each command.

Invalid models, for instance, include:
- Cheese with expiry date later than manufacture date
- Completed order but with incorrect quantity/type of cheese(s) assigned to it.

### PR DESCRIPTION
**Pull request by daniellau88**
- Add validation for all models
- Update initial data

### CODE REVIEW

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java [hunk 1]
```diff
@@ -83,6 +83,8 @@ public AddressBook toModelType() throws IllegalValueException {
             addressBook.addOrder(order);
         }
 
+        addressBook.checkAddressBook();
```
Comment (weixue123) [inline src/main/java/seedu/address/storage/JsonSerializableAddressBook.java:86]: The two ways when handling invalid data file:
1. Data file not in correct format -> warning -> start with an empty address book.
2. Data file not in correct format -> IllegalArgumentException -> app does not start.

Should we standardize this to one method??

File: src/main/java/seedu/address/model/cheese/Cheese.java [hunk 2]
```diff
@@ -69,6 +71,25 @@ public boolean getAssignStatus() {
...
+     * Checks whether the given parameters are valid for an order
+     */
+    public static void checkCheeseArguments(CheeseType cheeseType, ManufactureDate manufactureDate,
+                                            MaturityDate maturityDate, ExpiryDate expiryDate,
+                                            CheeseId cheeseId, boolean isAssigned) {
+        if (maturityDate != null) {
+            checkArgument(maturityDate.isAfter(manufactureDate),
+                "The maturity date of the cheese should be after the manufacture date.");
+        }
+
```
Comment (weixue123) [inline src/main/java/seedu/address/model/cheese/Cheese.java:84]: I think we can add in a case to handle when the user keys in an expiry date but not a maturity date when adding a cheese.

Anyway, since we are at this topic: I was thinking, we may want to consider dropping certain attributes from the models. For example only, since we have only 1 week left to add features, I think we may not have the time to implement features that deal with the cheeses' manufacture date, maturity date, etc.

We can always leave the clean up to v1.4, so it's just something to think about now? Should discuss more during Saturday's meeting.

File: src/main/java/seedu/address/model/AddressBook.java [hunk 3]
```diff
@@ -225,6 +231,50 @@ public void updateCheesesStatus(Set<CheeseId> cheesesAssigned) {
...
+            CheeseType expectedCheeseType = order.getCheeseType();
+
+            Set<CheeseId> cheeseIds = order.getCheeses();
+            OrderId orderId = order.getOrderId();
+
+            if (cheeseIds.size() > 0) {
+                for (CheeseId cheeseId : cheeseIds) {
+                    checkArgument(cheeseIdMap.containsKey(cheeseId),
+                        "Order " + orderId + "'s cheese ID does not exist.");
+
```
Comment (weixue123) [inline src/main/java/seedu/address/model/AddressBook.java:307]: I think it's okay if the cheese ID does not currently exist?

Consider the following scenario:
- User adds a new cheese (CheeseID = 1, CheeseType = Gouda, Quantity = 1)
- User adds a new order (OrderID = 1, CheeseType = Gouda, Quantity = 1)
- User completes Order 1 with Cheese 1.
- User deletes Cheese 1 (we currently allow this to happen without changing the order to which the cheese was assigned).
- User close the app.
- User reopens the app and runs into an IllegalArgumentException because CheeseID 1 no longer exist.

File: src/main/java/seedu/address/model/AddressBook.java [hunk 4]
```diff
@@ -225,6 +231,50 @@ public void updateCheesesStatus(Set<CheeseId> cheesesAssigned) {
...
+        for (Order order : orders.asUnmodifiableObservableList()) {
+            CustomerId customerId = order.getCustomerId();
+            checkArgument(customerIdSet.contains(customerId), "Order "
+                + order.getOrderId() + "'s customer ID does not exist.");
+
+            CheeseType expectedCheeseType = order.getCheeseType();
+
+            Set<CheeseId> cheeseIds = order.getCheeses();
+            OrderId orderId = order.getOrderId();
+
```
Comment (weixue123) [inline src/main/java/seedu/address/model/AddressBook.java:299]: We can also check to ensure that an incomplete order's cheeseIds is empty.

If not, the app can start without errors or warnings even when there's an order in the data file like this:
Screen Shot 2021-03-24 at 3 51 06 PM

**Review by weixue123 — COMMENTED** [review]
Also, when the user enters a command that will lead to an invalid model, can we reflect some messages to the UI? (Like how we currently handle parse exceptions).

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java (hunk 1 above)
Comment (daniellau88) [reply src/main/java/seedu/address/storage/JsonSerializableAddressBook.java:86]: I think would be good if it is the 1st case (less bugs when they smoke test)

File: src/main/java/seedu/address/model/cheese/Cheese.java (hunk 2 above)
Comment (daniellau88) [reply src/main/java/seedu/address/model/cheese/Cheese.java:84]: Which would you suggest to drop? If we want, we can just keep expiry and manufacture date (then I can add one more case in the AddressBook to ensure that the Cheese's manufacture date must be after the order's order date)

File: src/main/java/seedu/address/model/AddressBook.java (hunk 3 above)
Comment (daniellau88) [reply src/main/java/seedu/address/model/AddressBook.java:307]: I think this might cause some trouble on our side cause imagine if Order shows all the cheeses that are assigned to it (and also cause order needs to check that the cheese is of the same type).

I think, we can possibly disallow cheese deletion if the cheese has been assigned? (cause I think delete cascading will be bad for this)

Comment (weixue123) [reply src/main/java/seedu/address/model/AddressBook.java:307]: I think disallowing cheese deletion after it has been assigned sounds good - it will be just like IRL where you can't throw away a cheese after assigning it to an order, for example.

File: src/main/java/seedu/address/model/cheese/Cheese.java (hunk 2 above)
Comment (weixue123) [reply src/main/java/seedu/address/model/cheese/Cheese.java:84]: This one you and Li Quan can decide? or you want to wait until Saturday to discuss also can.

And then, actually a cheese manufacture date don't necessarily have to be after an order's order date right? Are you referring to the order's completed date instead? If so then sounds good!

File: src/main/java/seedu/address/storage/JsonSerializableAddressBook.java (hunk 1 above)
Comment (weixue123) [reply src/main/java/seedu/address/storage/JsonSerializableAddressBook.java:86]: kk

File: src/main/java/seedu/address/model/cheese/Cheese.java (hunk 2 above)
Comment (daniellau88) [reply src/main/java/seedu/address/model/cheese/Cheese.java:84]: Will discuss on Saturday

**Review by weixue123 — APPROVED** [review]

**Comment by weixue123** [comment]
loooks good to me!
