### PR TITLE
Model Validation Bug Fixes

### LINKED ISSUE #54: [PE-D] The date in addcheese command raises bugs
when type in : addcheese t/type 2 q/10 d/2020-01-01 m/2020-02-01 d/2019-01-01, in this case the expire date is before manufacture date, the command can still work.
Also, the expire date becomes manufacture date.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: skinnychenpi/ped#1

### LINKED ISSUE #78: [PE-D] addcheese e/ and m/ not working
In the User Guide, the e/ and m/ input seems to be optional, but there is no mention that I cannot use "addcheese q/1 t/brie m/02/02/2020" or "addcheese q/1 t/brie e/02/02/2020", which should work as I am just including optional inputs. However, these 2 commands that I mentioned does not work.
Below is the section on addcheese in the User Guide

Below is when I tried to execute "addcheese q/1 t/brie m/02/02/2020"

Below is when I tried to execute "addcheese q/1 t/brie e/02/02/2020"

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yeoutzer/ped#15

### LINKED ISSUE #79: [PE-D] Addorder order date
Assuming that the order's order date is the date where the customer requests the order of the cheese. The user should not be able to add an order with the order date that is way into the future. For example, today is 3/4/2021, the user should not be able to add an order with the order date of "01/01/2022".

Now assuming that the order's order date is the date where the user should complete the order by, the user should be able to complete an order before the order's order date, but it is not allowed.
This is after I added the specified "random" cheese required to complete the order

This is after I tried completing the order, which I got an error.

There is also no mention of what the order date is for, not in the User Guide or the application. For the date when the order was requested or the order the order should be completed by.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: yeoutzer/ped#16

### LINKED ISSUE #87: [PE-D] Error editing Cheese's manufacture date in some cases
Following the `editcheese`'s command, I am unable to edit the manufacturing date of the cheese when using **certain** values. However, this only works for certain scenarios.

Editing of cheese work for the provided example command as given in the User Guide `editcheese 1 t/Parmesan d/2021-03-12` which results in successful update.

However, when I try to edit the manufacturing date to another date using this command: `editcheese 1 t/Parmesan d/2021-06-12` it **does not work** and no error is shown.

[2021-04-03_143948.mp4](https://raw.githubusercontent.com/jasaaanlim/ped/main/files/6a32e959-cda6-45fb-98d2-52479f777fb5.mp4)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: jasaaanlim/ped#5

### LINKED ISSUE #88: [PE-D] Unable to edit Cheese's maturity date at all
Following the command format to edit the maturity date: `editcheese 1 t/Parmesan m/2021-03-12` does not work at all.

Command also does not work for purely editing maturity date: `editcheese 1 m/2021-03-12`

After running the command nothing happens, no error message or prompts.

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: jasaaanlim/ped#6

### LINKED ISSUE #106: [PE-D] Order date can be set to date in the future
user input: addorder t/Cheese Test 2 q/1 p/87438807 d/2022-12-30

result:

very minor flaw, not sure if it is feasible to set order dates that have not occurred yet? doesn't really make sense to have an order date that is in the future (i tested year 2022), could consider limiting the order date to present day? :)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: wei-yutong/ped#1

### LINKED ISSUE #107: [PE-D] addcheese not giving error message when date inputs are invalid
user input: 
addcheese t/Cheese Test 3 q/1 d/2020-12-30 m/2019-01-20 e/2021-02-30

addcheese t/Cheese Test 3 q/1 d/2020-12-30 m/2020-01-20 e/2019-02-30

i understand that [d/MANUFACTURE_DATE] should be before [m/MATURITY_DATE] should be before [d/EXPIRY_DATE], but when i enter [m/MATURITY_DATE] or [d/EXPIRY_DATE] as a date before [d/MANUFACTURE_DATE], no error message is shown. there is no response from the application at all although this user input is invalid.

perhaps you should suggest to the user to enter valid dates for each component. 

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: wei-yutong/ped#2

### LINKED ISSUE #109: [PE-D] editcheese not throwing error for invalid user input
user input: editcheese 1 t/Parmesan d/2020-12-30 m/2022-03-20 e/2021-02-30

similar to the addcheese issue, when the one of the dates are invalid (m/ is before e/), no error message is thrown. the application appears to have no response at all. 

perhaps an error message should be shown to show the user what inputs are valid. :)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: wei-yutong/ped#4

### PR DESCRIPTION
**Pull request by daniellau88**

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/EditCustomerCommand.java [hunk 1]
```diff
@@ -104,7 +105,13 @@ private static Customer createEditedCustomer(Customer customerToEdit,
         Set<Tag> updatedTags = editCustomerDescriptor.getTags().orElse(customerToEdit.getTags());
         CustomerId id = customerToEdit.getId();
 
-        return new Customer(updatedName, updatedPhone, updatedEmail, updatedAddress, updatedTags, id);
+        Customer retCustomer;
+        try {
+            retCustomer = new Customer(updatedName, updatedPhone, updatedEmail, updatedAddress, updatedTags, id);
+        } catch (IllegalArgumentException e) {
+            throw new CommandException(e.getMessage());
```
Comment (aaronsms) [inline src/main/java/seedu/address/logic/commands/EditCustomerCommand.java]: This should be fine but what model validation logic does Customer have?

**Review by aaronsms — APPROVED** [review]
All looks okay to me! Just want to clarify what model validation logic there is for Customer class and whether the try-catch is necessary.

File: src/main/java/seedu/address/logic/commands/EditCustomerCommand.java (hunk 1 above)
Comment (aaronsms) [reply src/main/java/seedu/address/logic/commands/EditCustomerCommand.java]: Shouldn't be necessary unless this is for future cases and consistency across the models.
